In [2]:
import numpy as np

In [3]:
#any other number

In [4]:
data = np.full((2,2), 99)

In [5]:
data

array([[99, 99],
       [99, 99]])

In [7]:
a = np.array([[2,2,2,2,2,3],[3,3,3,3,3,3]])

In [8]:
a

array([[2, 2, 2, 2, 2, 3],
       [3, 3, 3, 3, 3, 3]])

In [9]:
np.full_like(a,44)

array([[44, 44, 44, 44, 44, 44],
       [44, 44, 44, 44, 44, 44]])

In [10]:
np.full(a.shape, 66)

array([[66, 66, 66, 66, 66, 66],
       [66, 66, 66, 66, 66, 66]])

In [19]:
#any random number
np.random.randn(2,2)

array([[-0.50185522, -0.05586057],
       [-0.50330364,  0.5771037 ]])

In [22]:
np.random.random_sample(a.shape)

array([[0.57989987, 0.69700015, 0.42986302, 0.55534189, 0.47593248,
        0.57671925],
       [0.27440987, 0.91557697, 0.92766536, 0.42935715, 0.3318099 ,
        0.14229693]])

In [24]:
np.random.randn(4,4)

array([[-0.85366901,  0.09753141, -0.12781952, -0.31771021],
       [ 0.51694076,  0.33247861,  0.20708756,  0.48872503],
       [ 0.53428473,  0.31271286, -0.51673871, -0.29730523],
       [ 0.71442575,  0.70745293,  1.98428699,  0.1002717 ]])

In [30]:
#random integer value
np.random.randint(10, size=(4,4))

array([[5, 0, 3, 5],
       [3, 8, 0, 5],
       [0, 7, 5, 3],
       [1, 8, 7, 3]])

In [32]:
np.random.randint(8, size=(10,10))

array([[6, 7, 2, 6, 3, 2, 7, 5, 2, 4],
       [0, 1, 4, 4, 4, 3, 0, 5, 7, 1],
       [4, 7, 6, 4, 7, 6, 2, 0, 2, 1],
       [1, 4, 2, 2, 2, 2, 1, 0, 2, 3],
       [6, 7, 4, 6, 0, 4, 3, 7, 7, 5],
       [3, 4, 2, 3, 4, 0, 3, 6, 2, 0],
       [0, 1, 3, 1, 6, 6, 1, 2, 2, 0],
       [4, 5, 2, 0, 4, 0, 3, 2, 2, 1],
       [2, 6, 4, 6, 1, 0, 0, 4, 2, 3],
       [6, 2, 1, 5, 6, 5, 5, 7, 4, 3]])

In [35]:
np.random.randint(1,3, size=(4,2))

array([[1, 2],
       [1, 1],
       [1, 1],
       [1, 1]])

In [37]:
#Identity Matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [51]:
# Repeat an array
arr = np.array([3,4,5])
r = np.repeat(arr, 5, axis=0)
print(r)

[3 3 3 3 3 4 4 4 4 4 5 5 5 5 5]


In [52]:
arr2 = np.array([4,3,2])
r2 = np.repeat(arr2, 5, axis=0)
print(r2)

[4 4 4 4 4 3 3 3 3 3 2 2 2 2 2]


In [53]:
arr = np.array([[3,4,5]])
r = np.repeat(arr, 5, axis=0)
print(r)

[[3 4 5]
 [3 4 5]
 [3 4 5]
 [3 4 5]
 [3 4 5]]


In [56]:
a = np.ones((5,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [62]:
b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [63]:
b[1:2,1:2] = 9

In [64]:
b

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [65]:
b

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [66]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [67]:
a[1:4,1:4] = b

In [68]:
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Copying Array

In [73]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


# Mathematic

In [74]:
a = np.array([1,2,3,4,5])

In [75]:
a + 2

array([3, 4, 5, 6, 7])

In [76]:
a - 2

array([-1,  0,  1,  2,  3])

In [77]:
a +=2

In [78]:
a

array([3, 4, 5, 6, 7])

In [79]:
a +=2

In [80]:
a

array([5, 6, 7, 8, 9])

In [86]:
print(a ** 2)

[25 36 49 64 81]


In [87]:
np.sin(a)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [89]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

# Linear Algebra

In [107]:
#matrix multiplication
a = np.ones((2,3), dtype='int32')
b = np.random.randint(5, size=(3,3))

c = np.matmul(a,b)
print(c)

[[5 5 8]
 [5 5 8]]


In [115]:
# find determinant

a = np.identity(5)
np.linalg.det(a)

1.0

# Statistic

In [116]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [118]:
np.max(arr)

8

In [120]:
np.min(arr)

1

In [128]:
np.max(arr, axis=1)

array([4, 8])

# Reorganizing Array

In [130]:
arr = np.random.randint(8, size=(4,4))
arr

array([[6, 7, 3, 3],
       [1, 3, 6, 0],
       [7, 5, 4, 1],
       [4, 6, 0, 4]])

In [144]:
arr.reshape((8,2))

array([[6, 7],
       [3, 3],
       [1, 3],
       [6, 0],
       [7, 5],
       [4, 1],
       [4, 6],
       [0, 4]])

In [150]:
a = np.ones((4,4))
b = np.zeros((4,4))

np.hstack((a,b))

array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

In [151]:
a = np.ones((4,4))
b = np.zeros((4,4))

np.vstack((a,b))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])