# Numpy

# The Basics

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [12]:
b = np.array([[1,2,3,4],[5,6,7,8]], dtype='int64')

In [7]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
#Get Type
a.dtype

dtype('int32')

In [13]:
#Get Dimention
b.ndim

2

In [14]:
#Get Shape
b.shape

(2, 4)

In [15]:
b.nbytes

64

In [16]:
b.itemsize

8

# Accessing/Changing Specific Element Row, Column

In [24]:
a = np.array([[1,2,3,4,5,6,7],[8,6,4,23,6,8,3]])

In [25]:
a.shape

(2, 7)

In [26]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  6,  4, 23,  6,  8,  3]])

In [28]:
a[1,3] = 66

In [29]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  6,  4, 66,  6,  8,  3]])

In [32]:
# Getting specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [33]:
# Getting specific Column
a[:, 3]

array([ 4, 66])

In [34]:
a[:,-2]

array([6, 8])

In [84]:
c = np.array([[[[1,2,3,4,5],[1,2,3,4,5]]],[[[1,2,3,4,5],[1,2,3,4,5]]]])

In [85]:
c.ndim

4

In [62]:
c[0] =1

In [63]:
c

array([[1, 1, 1, 1, 1],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [64]:
c[3] = 1

In [65]:
c

array([[1, 1, 1, 1, 1],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 1, 1, 1, 1]])

In [66]:
c[1:3,1:4] = 0

In [67]:
c[:,4] = 1

In [68]:
c

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [75]:
c[0:,1:-1] = 0

In [77]:
c[1:3,0:] = 0

In [78]:
c

array([[1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1]])

# 3-D Array

In [87]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [89]:
a.ndim

3

In [90]:
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [95]:
a[0,1,1] = 8

In [96]:
a

array([[[1, 2],
        [3, 8]],

       [[5, 6],
        [7, 8]]])

# Initializing different types of Array

In [103]:
a = np.zeros(6)

In [104]:
a

array([0., 0., 0., 0., 0., 0.])

In [108]:
a = np.zeros((9,6))

In [109]:
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [110]:
b = np.ones(2)

In [111]:
b

array([1., 1.])

In [123]:
b = np.ones((3,3,5), dtype='int32')

In [124]:
b

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [125]:
b.itemsize

4